name: ⭐ Feature or enhancement request
description: Propose something new.
labels:
- enhancement
body:
- type: markdown
  attributes:
    value: Please make sure to [search for existing issues](https://github.com/mienaiyami/yomikiru/issues?q=) before filing a new one!

- type: markdown
  attributes:
    value: Please limit one request per issue.

- type: dropdown
  attributes:
    label: Type of reader (if reader related)
    options:
      - image
      - epub

- type: textarea
  attributes: 
    label: Description of the new feature / enhancement
    placeholder: What is the expected behavior of the proposed feature?
  validations:
    required: true
- type: textarea
  attributes:
    label: Scenario when this would be used?
    placeholder: What is the scenario this would be used?
  validations:
    required: false
- type: textarea
  attributes:
    label: Supporting information
  validations:
    required: false